name: Update HTML with Markdown

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert Markdown files to HTML
        run: |
          mkdir -p ragas/html
          for file in ragas/*.md; do
            # Extract filename without extension
            filename=$(basename "$file" .md)
            # Convert each Markdown file to HTML and save it in the 'ragas/html' directory
            pandoc -s "$file" -o "ragas/html/${filename}.html"
          done

      - name: Display converted HTML files
        run: |
          ls ragas/html
          cat ragas/html/*.html

      - name: Update index.html with links to HTML files
        run: |
          # Generate links for each HTML file
          echo '<!-- Links to Markdown Content -->' > links.html
          for file in ragas/html/*.html; do
            filename=$(basename "$file")
            # Create a link for each HTML file
            echo "<a href=\"ragas/html/${filename}\">${filename}</a><br>" >> links.html
          done
          # Inject links into index.html
          sed -i '/<!-- Links to Markdown Content -->/r links.html' index.html
          sed -i '/<!-- Links to Markdown Content -->/d' index.html

      - name: Display index.html after update
        run: |
          cat index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./
